#ifndef RISCV_TIMING_H
#define RISCV_TIMING_H

typedef enum {
    TC_UNKNOWN,
    TC_ARITH,
    TC_MUL,
    TC_DIV,
    TC_JB,
    TC_CSR,
    TC_LD,
    TC_ST,
} timing_category_t;

typedef enum {
    TTA_LUI,
    TTA_AUIPC,
    TTA_ADD,
    TTA_SUB,
    TTA_SLT,
    TTA_SLTU,
    TTA_SEQ,
    TTA_XOR,
    TTA_OR,
    TTA_AND,
    TTA_SLL,
    TTA_SRL,
    TTA_SRA,
    TTA_MAX,
    TTA_MAXU,
    TTA_MIN,
    TTA_MINU,
    TTA_CLZ,
    TTA_CTZ,
    TTA_CPOP,
    TTA_GREV,
    TTA_NOT,
    TTA_NEG,
    TTA_SEXTB,
    TTA_ZEXTB,
    TTA_SEXTH,
    TTA_ZEXTH,
    TTA_ANDN,
    TTA_ORN,
    TTA_XNOR,
    TTA_ROL,
    TTA_ROR,
    TTA_SH_ADD,
    TTA_BCLR,
    TTA_BSET,
    TTA_BINV,
    TTA_BEXT,
    TTA_CMOV,
    TTA_FSL,
    TTA_FSR,
    TTA_BFA,
    TTA_BFM,
    TTA_BFP,
    TTA_BFF,
    TTA_BFX,
    TTA_BFS,
    TTA_GORC,
} timing_type_arith_t;

typedef enum {
    TTM_MUL,
    TTM_MULH,
    TTM_MULHU,
    TTM_MULHSU,
} timing_type_mul_t;

typedef enum {
    TTD_DIV,
    TTD_DIVU,
    TTD_REM,
    TTD_REMU,
} timing_type_div_t;

typedef enum {
    TTJ_JAL,
    TTJ_JALR,
    TTJ_BCOND,
} timing_type_jb_t;

typedef enum {
    TTC_CSRRW,
    TTC_CSRRS,
    TTC_CSRRC,
    TTC_ECALL,
    TTC_MRET,
    TTC_EBREAK,
    TTC_FENCE_I,
} timing_type_csr_t;

typedef enum {
    TTL_LB,
    TTL_LH,
    TTL_LW,
} timing_type_ld_t;

typedef enum {
    TTS_SB,
    TTS_SH,
    TTS_SW,
} timing_type_st_t;

typedef enum {
    TTU_UNKNOWN,
} timing_type_unknown_t;

#define MKTIMING(cat, type) (((cat)<<16)|(type))

#define MKTIMING_ARITH(opc) MKTIMING(TC_ARITH, TTA_##opc)
#define MKTIMING_MUL(opc)   MKTIMING(TC_MUL,   TTM_##opc)
#define MKTIMING_DIV(opc)   MKTIMING(TC_DIV,   TTD_##opc)
#define MKTIMING_JB(opc)    MKTIMING(TC_JB,    TTJ_##opc)
#define MKTIMING_CSR(opc)   MKTIMING(TC_CSR,   TTC_##opc)
#define MKTIMING_LD(opc)    MKTIMING(TC_LD,    TTL_##opc)
#define MKTIMING_ST(opc)    MKTIMING(TC_ST,    TTS_##opc)
#define MKTIMING_UNKNOWN()  MKTIMING(TC_UNKNOWN, TTU_UNKNOWN)

#define TIMING_add MKTIMING_ARITH(ADD)
#define TIMING_add_uw MKTIMING_UNKNOWN()
#define TIMING_addi MKTIMING_ARITH(ADD)
#define TIMING_addiw MKTIMING_UNKNOWN()
#define TIMING_addw MKTIMING_UNKNOWN()
#define TIMING_aes32dsi MKTIMING_UNKNOWN()
#define TIMING_aes32dsmi MKTIMING_UNKNOWN()
#define TIMING_aes32esi MKTIMING_UNKNOWN()
#define TIMING_aes32esmi MKTIMING_UNKNOWN()
#define TIMING_aes64ds MKTIMING_UNKNOWN()
#define TIMING_aes64dsm MKTIMING_UNKNOWN()
#define TIMING_aes64es MKTIMING_UNKNOWN()
#define TIMING_aes64esm MKTIMING_UNKNOWN()
#define TIMING_aes64im MKTIMING_UNKNOWN()
#define TIMING_aes64ks1i MKTIMING_UNKNOWN()
#define TIMING_aes64ks2 MKTIMING_UNKNOWN()
#define TIMING_amoadd_b MKTIMING_UNKNOWN()
#define TIMING_amoadd_d MKTIMING_UNKNOWN()
#define TIMING_amoadd_h MKTIMING_UNKNOWN()
#define TIMING_amoadd_w MKTIMING_UNKNOWN()
#define TIMING_amoand_b MKTIMING_UNKNOWN()
#define TIMING_amoand_d MKTIMING_UNKNOWN()
#define TIMING_amoand_h MKTIMING_UNKNOWN()
#define TIMING_amoand_w MKTIMING_UNKNOWN()
#define TIMING_amocas_b MKTIMING_UNKNOWN()
#define TIMING_amocas_d MKTIMING_UNKNOWN()
#define TIMING_amocas_h MKTIMING_UNKNOWN()
#define TIMING_amocas_q MKTIMING_UNKNOWN()
#define TIMING_amocas_w MKTIMING_UNKNOWN()
#define TIMING_amomax_b MKTIMING_UNKNOWN()
#define TIMING_amomax_d MKTIMING_UNKNOWN()
#define TIMING_amomax_h MKTIMING_UNKNOWN()
#define TIMING_amomax_w MKTIMING_UNKNOWN()
#define TIMING_amomaxu_b MKTIMING_UNKNOWN()
#define TIMING_amomaxu_d MKTIMING_UNKNOWN()
#define TIMING_amomaxu_h MKTIMING_UNKNOWN()
#define TIMING_amomaxu_w MKTIMING_UNKNOWN()
#define TIMING_amomin_b MKTIMING_UNKNOWN()
#define TIMING_amomin_d MKTIMING_UNKNOWN()
#define TIMING_amomin_h MKTIMING_UNKNOWN()
#define TIMING_amomin_w MKTIMING_UNKNOWN()
#define TIMING_amominu_b MKTIMING_UNKNOWN()
#define TIMING_amominu_d MKTIMING_UNKNOWN()
#define TIMING_amominu_h MKTIMING_UNKNOWN()
#define TIMING_amominu_w MKTIMING_UNKNOWN()
#define TIMING_amoor_b MKTIMING_UNKNOWN()
#define TIMING_amoor_d MKTIMING_UNKNOWN()
#define TIMING_amoor_h MKTIMING_UNKNOWN()
#define TIMING_amoor_w MKTIMING_UNKNOWN()
#define TIMING_amoswap_b MKTIMING_UNKNOWN()
#define TIMING_amoswap_d MKTIMING_UNKNOWN()
#define TIMING_amoswap_h MKTIMING_UNKNOWN()
#define TIMING_amoswap_w MKTIMING_UNKNOWN()
#define TIMING_amoxor_b MKTIMING_UNKNOWN()
#define TIMING_amoxor_d MKTIMING_UNKNOWN()
#define TIMING_amoxor_h MKTIMING_UNKNOWN()
#define TIMING_amoxor_w MKTIMING_UNKNOWN()
#define TIMING_and        MKTIMING_ARITH(AND)
#define TIMING_andi       MKTIMING_ARITH(AND)
#define TIMING_andn       MKTIMING_ARITH(ANDN)
#define TIMING_auipc      MKTIMING_ARITH(AUIPC)
#define TIMING_bclr       MKTIMING_ARITH(BCLR)
#define TIMING_bclri      MKTIMING_ARITH(BCLR)
#define TIMING_beq        MKTIMING_JB(BCOND)
#define TIMING_bext       MKTIMING_ARITH(BEXT)
#define TIMING_bexti      MKTIMING_ARITH(BEXT)
#define TIMING_bge        MKTIMING_JB(BCOND)
#define TIMING_bgeu       MKTIMING_JB(BCOND)
#define TIMING_binv       MKTIMING_ARITH(BINV)
#define TIMING_binvi      MKTIMING_ARITH(BINV)
#define TIMING_blt        MKTIMING_JB(BCOND)
#define TIMING_bltu       MKTIMING_JB(BCOND)
#define TIMING_bne        MKTIMING_JB(BCOND)
#define TIMING_bset       MKTIMING_ARITH(BSET)
#define TIMING_bseti      MKTIMING_ARITH(BSET)
#define TIMING_c_add      MKTIMING_ARITH(ADD)
#define TIMING_c_addi     MKTIMING_ARITH(ADD)
#define TIMING_c_addi16sp MKTIMING_ARITH(ADD)
#define TIMING_c_addi4spn MKTIMING_ARITH(ADD)
#define TIMING_c_addiw MKTIMING_UNKNOWN()
#define TIMING_c_addw MKTIMING_UNKNOWN()
#define TIMING_c_and      MKTIMING_ARITH(AND)
#define TIMING_c_andi     MKTIMING_ARITH(AND)
#define TIMING_c_beqz     MKTIMING_JB(BCOND)
#define TIMING_c_bnez     MKTIMING_JB(BCOND)
#define TIMING_c_ebreak   MKTIMING_CSR(EBREAK)
#define TIMING_c_fld MKTIMING_UNKNOWN()
#define TIMING_c_fldsp MKTIMING_UNKNOWN()
#define TIMING_c_flw MKTIMING_UNKNOWN()
#define TIMING_c_flwsp MKTIMING_UNKNOWN()
#define TIMING_c_fsd MKTIMING_UNKNOWN()
#define TIMING_c_fsdsp MKTIMING_UNKNOWN()
#define TIMING_c_fsw MKTIMING_UNKNOWN()
#define TIMING_c_fswsp MKTIMING_UNKNOWN()
#define TIMING_c_j        MKTIMING_JB(JAL)
#define TIMING_c_jal      MKTIMING_JB(JAL)
#define TIMING_c_jalr     MKTIMING_JB(JALR)
#define TIMING_c_jr       MKTIMING_JB(JALR)
#define TIMING_c_ld MKTIMING_UNKNOWN()
#define TIMING_c_ldsp MKTIMING_UNKNOWN()
#define TIMING_c_li       MKTIMING_ARITH(ADD)
#define TIMING_c_lui      MKTIMING_ARITH(LUI)
#define TIMING_c_lw       MKTIMING_LD(LW)
#define TIMING_c_lwsp     MKTIMING_LD(LW)
#define TIMING_c_mop_1 MKTIMING_UNKNOWN()
#define TIMING_c_mop_11 MKTIMING_UNKNOWN()
#define TIMING_c_mop_13 MKTIMING_UNKNOWN()
#define TIMING_c_mop_15 MKTIMING_UNKNOWN()
#define TIMING_c_mop_3 MKTIMING_UNKNOWN()
#define TIMING_c_mop_5 MKTIMING_UNKNOWN()
#define TIMING_c_mop_7 MKTIMING_UNKNOWN()
#define TIMING_c_mop_9 MKTIMING_UNKNOWN()
#define TIMING_c_mop_n MKTIMING_UNKNOWN()
#define TIMING_c_mul      MKTIMING_MUL(MUL)
#define TIMING_c_mv       MKTIMING_ARITH(ADD)
#define TIMING_c_nop      MKTIMING_ARITH(ADD)
#define TIMING_c_not      MKTIMING_ARITH(NOT)
#define TIMING_c_or       MKTIMING_ARITH(OR)
#define TIMING_c_sd MKTIMING_UNKNOWN()
#define TIMING_c_sdsp MKTIMING_UNKNOWN()
#define TIMING_c_sext_b   MKTIMING_ARITH(SEXTB)
#define TIMING_c_sext_h   MKTIMING_ARITH(SEXTH)
#define TIMING_c_slli     MKTIMING_ARITH(SLL)
#define TIMING_c_srai     MKTIMING_ARITH(SRA)
#define TIMING_c_srli     MKTIMING_ARITH(SRL)
#define TIMING_c_sspopchk_x5 MKTIMING_UNKNOWN()
#define TIMING_c_sspush_x1 MKTIMING_UNKNOWN()
#define TIMING_c_sub      MKTIMING_ARITH(SUB)
#define TIMING_c_subw MKTIMING_UNKNOWN()
#define TIMING_c_sw       MKTIMING_ST(SW)
#define TIMING_c_swsp     MKTIMING_ST(SW)
#define TIMING_c_xor      MKTIMING_ARITH(XOR)
#define TIMING_c_zext_b   MKTIMING_ARITH(ZEXTB)
#define TIMING_c_zext_h   MKTIMING_ARITH(ZEXTH)
#define TIMING_c_zext_w MKTIMING_UNKNOWN()
#define TIMING_cbo_clean MKTIMING_UNKNOWN()
#define TIMING_cbo_flush MKTIMING_UNKNOWN()
#define TIMING_cbo_inval MKTIMING_UNKNOWN()
#define TIMING_cbo_zero MKTIMING_UNKNOWN()
#define TIMING_clmul MKTIMING_UNKNOWN()
#define TIMING_clmulh MKTIMING_UNKNOWN()
#define TIMING_clmulr MKTIMING_UNKNOWN()
#define TIMING_clz        MKTIMING_ARITH(CLZ)
#define TIMING_clzw MKTIMING_UNKNOWN()
#define TIMING_cm_jalt MKTIMING_UNKNOWN()
#define TIMING_cm_mva01s MKTIMING_UNKNOWN()
#define TIMING_cm_mvsa01 MKTIMING_UNKNOWN()
#define TIMING_cm_pop MKTIMING_UNKNOWN()
#define TIMING_cm_popret MKTIMING_UNKNOWN()
#define TIMING_cm_popretz MKTIMING_UNKNOWN()
#define TIMING_cm_push MKTIMING_UNKNOWN()
#define TIMING_cpop MKTIMING_UNKNOWN()
#define TIMING_cpopw MKTIMING_UNKNOWN()
#define TIMING_csrrc      MKTIMING_CSR(CSRRC)
#define TIMING_csrrci     MKTIMING_CSR(CSRRC)
#define TIMING_csrrs      MKTIMING_CSR(CSRRS)
#define TIMING_csrrsi     MKTIMING_CSR(CSRRS)
#define TIMING_csrrw      MKTIMING_CSR(CSRRW)
#define TIMING_csrrwi     MKTIMING_CSR(CSRRW)
#define TIMING_ctz        MKTIMING_ARITH(CTZ)
#define TIMING_ctzw MKTIMING_UNKNOWN()
#define TIMING_czero_eqz MKTIMING_UNKNOWN()
#define TIMING_czero_nez MKTIMING_UNKNOWN()
#define TIMING_div        MKTIMING_DIV(DIV)
#define TIMING_divu       MKTIMING_DIV(DIVU)
#define TIMING_divuw MKTIMING_UNKNOWN()
#define TIMING_divw MKTIMING_UNKNOWN()
#define TIMING_dret MKTIMING_UNKNOWN()
#define TIMING_ebreak     MKTIMING_CSR(EBREAK)
#define TIMING_ecall      MKTIMING_CSR(ECALL)
#define TIMING_fadd_d MKTIMING_UNKNOWN()
#define TIMING_fadd_h MKTIMING_UNKNOWN()
#define TIMING_fadd_q MKTIMING_UNKNOWN()
#define TIMING_fadd_s MKTIMING_UNKNOWN()
#define TIMING_fclass_d MKTIMING_UNKNOWN()
#define TIMING_fclass_h MKTIMING_UNKNOWN()
#define TIMING_fclass_q MKTIMING_UNKNOWN()
#define TIMING_fclass_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_bf16_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_d_h MKTIMING_UNKNOWN()
#define TIMING_fcvt_d_l MKTIMING_UNKNOWN()
#define TIMING_fcvt_d_lu MKTIMING_UNKNOWN()
#define TIMING_fcvt_d_q MKTIMING_UNKNOWN()
#define TIMING_fcvt_d_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_d_w MKTIMING_UNKNOWN()
#define TIMING_fcvt_d_wu MKTIMING_UNKNOWN()
#define TIMING_fcvt_h_d MKTIMING_UNKNOWN()
#define TIMING_fcvt_h_l MKTIMING_UNKNOWN()
#define TIMING_fcvt_h_lu MKTIMING_UNKNOWN()
#define TIMING_fcvt_h_q MKTIMING_UNKNOWN()
#define TIMING_fcvt_h_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_h_w MKTIMING_UNKNOWN()
#define TIMING_fcvt_h_wu MKTIMING_UNKNOWN()
#define TIMING_fcvt_l_d MKTIMING_UNKNOWN()
#define TIMING_fcvt_l_h MKTIMING_UNKNOWN()
#define TIMING_fcvt_l_q MKTIMING_UNKNOWN()
#define TIMING_fcvt_l_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_lu_d MKTIMING_UNKNOWN()
#define TIMING_fcvt_lu_h MKTIMING_UNKNOWN()
#define TIMING_fcvt_lu_q MKTIMING_UNKNOWN()
#define TIMING_fcvt_lu_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_q_d MKTIMING_UNKNOWN()
#define TIMING_fcvt_q_h MKTIMING_UNKNOWN()
#define TIMING_fcvt_q_l MKTIMING_UNKNOWN()
#define TIMING_fcvt_q_lu MKTIMING_UNKNOWN()
#define TIMING_fcvt_q_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_q_w MKTIMING_UNKNOWN()
#define TIMING_fcvt_q_wu MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_bf16 MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_d MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_h MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_l MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_lu MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_q MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_w MKTIMING_UNKNOWN()
#define TIMING_fcvt_s_wu MKTIMING_UNKNOWN()
#define TIMING_fcvt_w_d MKTIMING_UNKNOWN()
#define TIMING_fcvt_w_h MKTIMING_UNKNOWN()
#define TIMING_fcvt_w_q MKTIMING_UNKNOWN()
#define TIMING_fcvt_w_s MKTIMING_UNKNOWN()
#define TIMING_fcvt_wu_d MKTIMING_UNKNOWN()
#define TIMING_fcvt_wu_h MKTIMING_UNKNOWN()
#define TIMING_fcvt_wu_q MKTIMING_UNKNOWN()
#define TIMING_fcvt_wu_s MKTIMING_UNKNOWN()
#define TIMING_fcvtmod_w_d MKTIMING_UNKNOWN()
#define TIMING_fdiv_d MKTIMING_UNKNOWN()
#define TIMING_fdiv_h MKTIMING_UNKNOWN()
#define TIMING_fdiv_q MKTIMING_UNKNOWN()
#define TIMING_fdiv_s MKTIMING_UNKNOWN()
#define TIMING_fence MKTIMING_UNKNOWN()
#define TIMING_fence_i    MKTIMING_CSR(FENCE_I)
#define TIMING_feq_d MKTIMING_UNKNOWN()
#define TIMING_feq_h MKTIMING_UNKNOWN()
#define TIMING_feq_q MKTIMING_UNKNOWN()
#define TIMING_feq_s MKTIMING_UNKNOWN()
#define TIMING_fld MKTIMING_UNKNOWN()
#define TIMING_fle_d MKTIMING_UNKNOWN()
#define TIMING_fle_h MKTIMING_UNKNOWN()
#define TIMING_fle_q MKTIMING_UNKNOWN()
#define TIMING_fle_s MKTIMING_UNKNOWN()
#define TIMING_fleq_d MKTIMING_UNKNOWN()
#define TIMING_fleq_h MKTIMING_UNKNOWN()
#define TIMING_fleq_q MKTIMING_UNKNOWN()
#define TIMING_fleq_s MKTIMING_UNKNOWN()
#define TIMING_flh MKTIMING_UNKNOWN()
#define TIMING_fli_d MKTIMING_UNKNOWN()
#define TIMING_fli_h MKTIMING_UNKNOWN()
#define TIMING_fli_q MKTIMING_UNKNOWN()
#define TIMING_fli_s MKTIMING_UNKNOWN()
#define TIMING_flq MKTIMING_UNKNOWN()
#define TIMING_flt_d MKTIMING_UNKNOWN()
#define TIMING_flt_h MKTIMING_UNKNOWN()
#define TIMING_flt_q MKTIMING_UNKNOWN()
#define TIMING_flt_s MKTIMING_UNKNOWN()
#define TIMING_fltq_d MKTIMING_UNKNOWN()
#define TIMING_fltq_h MKTIMING_UNKNOWN()
#define TIMING_fltq_q MKTIMING_UNKNOWN()
#define TIMING_fltq_s MKTIMING_UNKNOWN()
#define TIMING_flw MKTIMING_UNKNOWN()
#define TIMING_fmadd_d MKTIMING_UNKNOWN()
#define TIMING_fmadd_h MKTIMING_UNKNOWN()
#define TIMING_fmadd_q MKTIMING_UNKNOWN()
#define TIMING_fmadd_s MKTIMING_UNKNOWN()
#define TIMING_fmax_d MKTIMING_UNKNOWN()
#define TIMING_fmax_h MKTIMING_UNKNOWN()
#define TIMING_fmax_q MKTIMING_UNKNOWN()
#define TIMING_fmax_s MKTIMING_UNKNOWN()
#define TIMING_fmaxm_d MKTIMING_UNKNOWN()
#define TIMING_fmaxm_h MKTIMING_UNKNOWN()
#define TIMING_fmaxm_q MKTIMING_UNKNOWN()
#define TIMING_fmaxm_s MKTIMING_UNKNOWN()
#define TIMING_fmin_d MKTIMING_UNKNOWN()
#define TIMING_fmin_h MKTIMING_UNKNOWN()
#define TIMING_fmin_q MKTIMING_UNKNOWN()
#define TIMING_fmin_s MKTIMING_UNKNOWN()
#define TIMING_fminm_d MKTIMING_UNKNOWN()
#define TIMING_fminm_h MKTIMING_UNKNOWN()
#define TIMING_fminm_q MKTIMING_UNKNOWN()
#define TIMING_fminm_s MKTIMING_UNKNOWN()
#define TIMING_fmsub_d MKTIMING_UNKNOWN()
#define TIMING_fmsub_h MKTIMING_UNKNOWN()
#define TIMING_fmsub_q MKTIMING_UNKNOWN()
#define TIMING_fmsub_s MKTIMING_UNKNOWN()
#define TIMING_fmul_d MKTIMING_UNKNOWN()
#define TIMING_fmul_h MKTIMING_UNKNOWN()
#define TIMING_fmul_q MKTIMING_UNKNOWN()
#define TIMING_fmul_s MKTIMING_UNKNOWN()
#define TIMING_fmv_d_x MKTIMING_UNKNOWN()
#define TIMING_fmv_h_x MKTIMING_UNKNOWN()
#define TIMING_fmv_w_x MKTIMING_UNKNOWN()
#define TIMING_fmv_x_d MKTIMING_UNKNOWN()
#define TIMING_fmv_x_h MKTIMING_UNKNOWN()
#define TIMING_fmv_x_w MKTIMING_UNKNOWN()
#define TIMING_fmvh_x_d MKTIMING_UNKNOWN()
#define TIMING_fmvh_x_q MKTIMING_UNKNOWN()
#define TIMING_fmvp_d_x MKTIMING_UNKNOWN()
#define TIMING_fmvp_q_x MKTIMING_UNKNOWN()
#define TIMING_fnmadd_d MKTIMING_UNKNOWN()
#define TIMING_fnmadd_h MKTIMING_UNKNOWN()
#define TIMING_fnmadd_q MKTIMING_UNKNOWN()
#define TIMING_fnmadd_s MKTIMING_UNKNOWN()
#define TIMING_fnmsub_d MKTIMING_UNKNOWN()
#define TIMING_fnmsub_h MKTIMING_UNKNOWN()
#define TIMING_fnmsub_q MKTIMING_UNKNOWN()
#define TIMING_fnmsub_s MKTIMING_UNKNOWN()
#define TIMING_fround_d MKTIMING_UNKNOWN()
#define TIMING_fround_h MKTIMING_UNKNOWN()
#define TIMING_fround_q MKTIMING_UNKNOWN()
#define TIMING_fround_s MKTIMING_UNKNOWN()
#define TIMING_froundnx_d MKTIMING_UNKNOWN()
#define TIMING_froundnx_h MKTIMING_UNKNOWN()
#define TIMING_froundnx_q MKTIMING_UNKNOWN()
#define TIMING_froundnx_s MKTIMING_UNKNOWN()
#define TIMING_fsd MKTIMING_UNKNOWN()
#define TIMING_fsgnj_d MKTIMING_UNKNOWN()
#define TIMING_fsgnj_h MKTIMING_UNKNOWN()
#define TIMING_fsgnj_q MKTIMING_UNKNOWN()
#define TIMING_fsgnj_s MKTIMING_UNKNOWN()
#define TIMING_fsgnjn_d MKTIMING_UNKNOWN()
#define TIMING_fsgnjn_h MKTIMING_UNKNOWN()
#define TIMING_fsgnjn_q MKTIMING_UNKNOWN()
#define TIMING_fsgnjn_s MKTIMING_UNKNOWN()
#define TIMING_fsgnjx_d MKTIMING_UNKNOWN()
#define TIMING_fsgnjx_h MKTIMING_UNKNOWN()
#define TIMING_fsgnjx_q MKTIMING_UNKNOWN()
#define TIMING_fsgnjx_s MKTIMING_UNKNOWN()
#define TIMING_fsh MKTIMING_UNKNOWN()
#define TIMING_fsq MKTIMING_UNKNOWN()
#define TIMING_fsqrt_d MKTIMING_UNKNOWN()
#define TIMING_fsqrt_h MKTIMING_UNKNOWN()
#define TIMING_fsqrt_q MKTIMING_UNKNOWN()
#define TIMING_fsqrt_s MKTIMING_UNKNOWN()
#define TIMING_fsub_d MKTIMING_UNKNOWN()
#define TIMING_fsub_h MKTIMING_UNKNOWN()
#define TIMING_fsub_q MKTIMING_UNKNOWN()
#define TIMING_fsub_s MKTIMING_UNKNOWN()
#define TIMING_fsw MKTIMING_UNKNOWN()
#define TIMING_gorci      MKTIMING_ARITH(GORC)
#define TIMING_grevi      MKTIMING_ARITH(GREV)
#define TIMING_hfence_gvma MKTIMING_UNKNOWN()
#define TIMING_hfence_vvma MKTIMING_UNKNOWN()
#define TIMING_hinval_gvma MKTIMING_UNKNOWN()
#define TIMING_hinval_vvma MKTIMING_UNKNOWN()
#define TIMING_hlv_b MKTIMING_UNKNOWN()
#define TIMING_hlv_bu MKTIMING_UNKNOWN()
#define TIMING_hlv_d MKTIMING_UNKNOWN()
#define TIMING_hlv_h MKTIMING_UNKNOWN()
#define TIMING_hlv_hu MKTIMING_UNKNOWN()
#define TIMING_hlv_w MKTIMING_UNKNOWN()
#define TIMING_hlv_wu MKTIMING_UNKNOWN()
#define TIMING_hlvx_hu MKTIMING_UNKNOWN()
#define TIMING_hlvx_wu MKTIMING_UNKNOWN()
#define TIMING_hsv_b MKTIMING_UNKNOWN()
#define TIMING_hsv_d MKTIMING_UNKNOWN()
#define TIMING_hsv_h MKTIMING_UNKNOWN()
#define TIMING_hsv_w MKTIMING_UNKNOWN()
#define TIMING_jal        MKTIMING_JB(JAL)
#define TIMING_jalr       MKTIMING_JB(JALR)
#define TIMING_lb         MKTIMING_LD(LB)
#define TIMING_lb_aq MKTIMING_UNKNOWN()
#define TIMING_lbu        MKTIMING_LD(LB)
#define TIMING_ld MKTIMING_UNKNOWN()
#define TIMING_ld_aq MKTIMING_UNKNOWN()
#define TIMING_lh         MKTIMING_LD(LH)
#define TIMING_lh_aq MKTIMING_UNKNOWN()
#define TIMING_lhu        MKTIMING_LD(LH)
#define TIMING_lpad MKTIMING_UNKNOWN()
#define TIMING_lr_d MKTIMING_UNKNOWN()
#define TIMING_lr_w MKTIMING_UNKNOWN()
#define TIMING_lui        MKTIMING_ARITH(LUI)
#define TIMING_lw         MKTIMING_LD(LW)
#define TIMING_lw_aq MKTIMING_UNKNOWN()
#define TIMING_lwu MKTIMING_UNKNOWN()
#define TIMING_max        MKTIMING_ARITH(MAX)
#define TIMING_maxu       MKTIMING_ARITH(MAXU)
#define TIMING_min        MKTIMING_ARITH(MIN)
#define TIMING_minu       MKTIMING_ARITH(MINU)
#define TIMING_mnret MKTIMING_UNKNOWN()
#define TIMING_mop_r_0 MKTIMING_UNKNOWN()
#define TIMING_mop_r_1 MKTIMING_UNKNOWN()
#define TIMING_mop_r_10 MKTIMING_UNKNOWN()
#define TIMING_mop_r_11 MKTIMING_UNKNOWN()
#define TIMING_mop_r_12 MKTIMING_UNKNOWN()
#define TIMING_mop_r_13 MKTIMING_UNKNOWN()
#define TIMING_mop_r_14 MKTIMING_UNKNOWN()
#define TIMING_mop_r_15 MKTIMING_UNKNOWN()
#define TIMING_mop_r_16 MKTIMING_UNKNOWN()
#define TIMING_mop_r_17 MKTIMING_UNKNOWN()
#define TIMING_mop_r_18 MKTIMING_UNKNOWN()
#define TIMING_mop_r_19 MKTIMING_UNKNOWN()
#define TIMING_mop_r_2 MKTIMING_UNKNOWN()
#define TIMING_mop_r_20 MKTIMING_UNKNOWN()
#define TIMING_mop_r_21 MKTIMING_UNKNOWN()
#define TIMING_mop_r_22 MKTIMING_UNKNOWN()
#define TIMING_mop_r_23 MKTIMING_UNKNOWN()
#define TIMING_mop_r_24 MKTIMING_UNKNOWN()
#define TIMING_mop_r_25 MKTIMING_UNKNOWN()
#define TIMING_mop_r_26 MKTIMING_UNKNOWN()
#define TIMING_mop_r_27 MKTIMING_UNKNOWN()
#define TIMING_mop_r_28 MKTIMING_UNKNOWN()
#define TIMING_mop_r_29 MKTIMING_UNKNOWN()
#define TIMING_mop_r_3 MKTIMING_UNKNOWN()
#define TIMING_mop_r_30 MKTIMING_UNKNOWN()
#define TIMING_mop_r_31 MKTIMING_UNKNOWN()
#define TIMING_mop_r_4 MKTIMING_UNKNOWN()
#define TIMING_mop_r_5 MKTIMING_UNKNOWN()
#define TIMING_mop_r_6 MKTIMING_UNKNOWN()
#define TIMING_mop_r_7 MKTIMING_UNKNOWN()
#define TIMING_mop_r_8 MKTIMING_UNKNOWN()
#define TIMING_mop_r_9 MKTIMING_UNKNOWN()
#define TIMING_mop_r_n MKTIMING_UNKNOWN()
#define TIMING_mop_rr_0 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_1 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_2 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_3 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_4 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_5 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_6 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_7 MKTIMING_UNKNOWN()
#define TIMING_mop_rr_n MKTIMING_UNKNOWN()
#define TIMING_mret       MKTIMING_CSR(MRET)
#define TIMING_mul        MKTIMING_MUL(MUL)
#define TIMING_mulh       MKTIMING_MUL(MULH)
#define TIMING_mulhsu     MKTIMING_MUL(MULHSU)
#define TIMING_mulhu      MKTIMING_MUL(MULHU)
#define TIMING_mulw MKTIMING_UNKNOWN()
#define TIMING_or         MKTIMING_ARITH(OR)
#define TIMING_ori        MKTIMING_ARITH(OR)
#define TIMING_orn        MKTIMING_ARITH(ORN)
#define TIMING_pack MKTIMING_ARITH(ZEXTH)
#define TIMING_packh MKTIMING_UNKNOWN()
#define TIMING_packw MKTIMING_UNKNOWN()
#define TIMING_pause MKTIMING_UNKNOWN()
#define TIMING_prefetch_i MKTIMING_UNKNOWN()
#define TIMING_prefetch_r MKTIMING_UNKNOWN()
#define TIMING_prefetch_w MKTIMING_UNKNOWN()
#define TIMING_rem        MKTIMING_DIV(REM)
#define TIMING_remu       MKTIMING_DIV(REMU)
#define TIMING_remuw MKTIMING_UNKNOWN()
#define TIMING_remw MKTIMING_UNKNOWN()
#define TIMING_rol        MKTIMING_ARITH(ROL)
#define TIMING_rolw MKTIMING_UNKNOWN()
#define TIMING_ror        MKTIMING_ARITH(ROR)
#define TIMING_rori       MKTIMING_ARITH(ROR)
#define TIMING_roriw MKTIMING_UNKNOWN()
#define TIMING_rorw MKTIMING_UNKNOWN()
#define TIMING_sb         MKTIMING_ST(SB)
#define TIMING_sb_rl MKTIMING_UNKNOWN()
#define TIMING_sc_d MKTIMING_UNKNOWN()
#define TIMING_sc_w MKTIMING_UNKNOWN()
#define TIMING_sctrclr MKTIMING_UNKNOWN()
#define TIMING_sd MKTIMING_UNKNOWN()
#define TIMING_sd_rl MKTIMING_UNKNOWN()
#define TIMING_sext_b     MKTIMING_ARITH(SEXTB)
#define TIMING_sext_h     MKTIMING_ARITH(SEXTH)
#define TIMING_sfence_inval_ir MKTIMING_UNKNOWN()
#define TIMING_sfence_vma MKTIMING_UNKNOWN()
#define TIMING_sfence_w_inval MKTIMING_UNKNOWN()
#define TIMING_sh         MKTIMING_ST(SH)
#define TIMING_sh1add     MKTIMING_ARITH(SH_ADD)
#define TIMING_sh1add_uw MKTIMING_UNKNOWN()
#define TIMING_sh2add     MKTIMING_ARITH(SH_ADD)
#define TIMING_sh2add_uw MKTIMING_UNKNOWN()
#define TIMING_sh3add     MKTIMING_ARITH(SH_ADD)
#define TIMING_sh3add_uw MKTIMING_UNKNOWN()
#define TIMING_sh_rl MKTIMING_UNKNOWN()
#define TIMING_sha256sig0 MKTIMING_UNKNOWN()
#define TIMING_sha256sig1 MKTIMING_UNKNOWN()
#define TIMING_sha256sum0 MKTIMING_UNKNOWN()
#define TIMING_sha256sum1 MKTIMING_UNKNOWN()
#define TIMING_sha512sig0 MKTIMING_UNKNOWN()
#define TIMING_sha512sig0h MKTIMING_UNKNOWN()
#define TIMING_sha512sig0l MKTIMING_UNKNOWN()
#define TIMING_sha512sig1 MKTIMING_UNKNOWN()
#define TIMING_sha512sig1h MKTIMING_UNKNOWN()
#define TIMING_sha512sig1l MKTIMING_UNKNOWN()
#define TIMING_sha512sum0 MKTIMING_UNKNOWN()
#define TIMING_sha512sum0r MKTIMING_UNKNOWN()
#define TIMING_sha512sum1 MKTIMING_UNKNOWN()
#define TIMING_sha512sum1r MKTIMING_UNKNOWN()
#define TIMING_shfli MKTIMING_UNKNOWN()
#define TIMING_sinval_vma MKTIMING_UNKNOWN()
#define TIMING_sll        MKTIMING_ARITH(SLL)
#define TIMING_slli       MKTIMING_ARITH(SLL)
#define TIMING_slli_rv32  MKTIMING_ARITH(SLL)
#define TIMING_slli_uw MKTIMING_UNKNOWN()
#define TIMING_slliw MKTIMING_UNKNOWN()
#define TIMING_sllw MKTIMING_UNKNOWN()
#define TIMING_slt        MKTIMING_ARITH(SLT)
#define TIMING_slti       MKTIMING_ARITH(SLT)
#define TIMING_sltiu      MKTIMING_ARITH(SLTU)
#define TIMING_sltu       MKTIMING_ARITH(SLTU)
#define TIMING_sm3p0 MKTIMING_UNKNOWN()
#define TIMING_sm3p1 MKTIMING_UNKNOWN()
#define TIMING_sm4ed MKTIMING_UNKNOWN()
#define TIMING_sm4ks MKTIMING_UNKNOWN()
#define TIMING_sra        MKTIMING_ARITH(SRA)
#define TIMING_srai       MKTIMING_ARITH(SRA)
#define TIMING_srai_rv32  MKTIMING_ARITH(SRA)
#define TIMING_sraiw MKTIMING_UNKNOWN()
#define TIMING_sraw MKTIMING_UNKNOWN()
#define TIMING_sret MKTIMING_UNKNOWN()
#define TIMING_srl        MKTIMING_ARITH(SRL)
#define TIMING_srli       MKTIMING_ARITH(SRL)
#define TIMING_srli_rv32  MKTIMING_ARITH(SRL)
#define TIMING_srliw MKTIMING_UNKNOWN()
#define TIMING_srlw MKTIMING_UNKNOWN()
#define TIMING_ssamoswap_d MKTIMING_UNKNOWN()
#define TIMING_ssamoswap_w MKTIMING_UNKNOWN()
#define TIMING_sspopchk_x1 MKTIMING_UNKNOWN()
#define TIMING_sspopchk_x5 MKTIMING_UNKNOWN()
#define TIMING_sspush_x1 MKTIMING_UNKNOWN()
#define TIMING_sspush_x5 MKTIMING_UNKNOWN()
#define TIMING_ssrdp MKTIMING_UNKNOWN()
#define TIMING_sub        MKTIMING_ARITH(SUB)
#define TIMING_subw MKTIMING_UNKNOWN()
#define TIMING_sw         MKTIMING_ST(SW)
#define TIMING_sw_rl MKTIMING_UNKNOWN()
#define TIMING_unshfli MKTIMING_UNKNOWN()
#define TIMING_vaadd_vv MKTIMING_UNKNOWN()
#define TIMING_vaadd_vx MKTIMING_UNKNOWN()
#define TIMING_vaaddu_vv MKTIMING_UNKNOWN()
#define TIMING_vaaddu_vx MKTIMING_UNKNOWN()
#define TIMING_vadc_vim MKTIMING_UNKNOWN()
#define TIMING_vadc_vvm MKTIMING_UNKNOWN()
#define TIMING_vadc_vxm MKTIMING_UNKNOWN()
#define TIMING_vadd_vi MKTIMING_UNKNOWN()
#define TIMING_vadd_vv MKTIMING_UNKNOWN()
#define TIMING_vadd_vx MKTIMING_UNKNOWN()
#define TIMING_vaesdf_vs MKTIMING_UNKNOWN()
#define TIMING_vaesdf_vv MKTIMING_UNKNOWN()
#define TIMING_vaesdm_vs MKTIMING_UNKNOWN()
#define TIMING_vaesdm_vv MKTIMING_UNKNOWN()
#define TIMING_vaesef_vs MKTIMING_UNKNOWN()
#define TIMING_vaesef_vv MKTIMING_UNKNOWN()
#define TIMING_vaesem_vs MKTIMING_UNKNOWN()
#define TIMING_vaesem_vv MKTIMING_UNKNOWN()
#define TIMING_vaeskf1_vi MKTIMING_UNKNOWN()
#define TIMING_vaeskf2_vi MKTIMING_UNKNOWN()
#define TIMING_vaesz_vs MKTIMING_UNKNOWN()
#define TIMING_vand_vi MKTIMING_UNKNOWN()
#define TIMING_vand_vv MKTIMING_UNKNOWN()
#define TIMING_vand_vx MKTIMING_UNKNOWN()
#define TIMING_vandn_vv MKTIMING_UNKNOWN()
#define TIMING_vandn_vx MKTIMING_UNKNOWN()
#define TIMING_vasub_vv MKTIMING_UNKNOWN()
#define TIMING_vasub_vx MKTIMING_UNKNOWN()
#define TIMING_vasubu_vv MKTIMING_UNKNOWN()
#define TIMING_vasubu_vx MKTIMING_UNKNOWN()
#define TIMING_vbrev8_v MKTIMING_UNKNOWN()
#define TIMING_vbrev_v MKTIMING_UNKNOWN()
#define TIMING_vclmul_vv MKTIMING_UNKNOWN()
#define TIMING_vclmul_vx MKTIMING_UNKNOWN()
#define TIMING_vclmulh_vv MKTIMING_UNKNOWN()
#define TIMING_vclmulh_vx MKTIMING_UNKNOWN()
#define TIMING_vclz_v MKTIMING_UNKNOWN()
#define TIMING_vcompress_vm MKTIMING_UNKNOWN()
#define TIMING_vcpop_m MKTIMING_UNKNOWN()
#define TIMING_vcpop_v MKTIMING_UNKNOWN()
#define TIMING_vctz_v MKTIMING_UNKNOWN()
#define TIMING_vdiv_vv MKTIMING_UNKNOWN()
#define TIMING_vdiv_vx MKTIMING_UNKNOWN()
#define TIMING_vdivu_vv MKTIMING_UNKNOWN()
#define TIMING_vdivu_vx MKTIMING_UNKNOWN()
#define TIMING_vfadd_vf MKTIMING_UNKNOWN()
#define TIMING_vfadd_vv MKTIMING_UNKNOWN()
#define TIMING_vfclass_v MKTIMING_UNKNOWN()
#define TIMING_vfcvt_f_x_v MKTIMING_UNKNOWN()
#define TIMING_vfcvt_f_xu_v MKTIMING_UNKNOWN()
#define TIMING_vfcvt_rtz_x_f_v MKTIMING_UNKNOWN()
#define TIMING_vfcvt_rtz_xu_f_v MKTIMING_UNKNOWN()
#define TIMING_vfcvt_x_f_v MKTIMING_UNKNOWN()
#define TIMING_vfcvt_xu_f_v MKTIMING_UNKNOWN()
#define TIMING_vfdiv_vf MKTIMING_UNKNOWN()
#define TIMING_vfdiv_vv MKTIMING_UNKNOWN()
#define TIMING_vfirst_m MKTIMING_UNKNOWN()
#define TIMING_vfmacc_vf MKTIMING_UNKNOWN()
#define TIMING_vfmacc_vv MKTIMING_UNKNOWN()
#define TIMING_vfmadd_vf MKTIMING_UNKNOWN()
#define TIMING_vfmadd_vv MKTIMING_UNKNOWN()
#define TIMING_vfmax_vf MKTIMING_UNKNOWN()
#define TIMING_vfmax_vv MKTIMING_UNKNOWN()
#define TIMING_vfmerge_vfm MKTIMING_UNKNOWN()
#define TIMING_vfmin_vf MKTIMING_UNKNOWN()
#define TIMING_vfmin_vv MKTIMING_UNKNOWN()
#define TIMING_vfmsac_vf MKTIMING_UNKNOWN()
#define TIMING_vfmsac_vv MKTIMING_UNKNOWN()
#define TIMING_vfmsub_vf MKTIMING_UNKNOWN()
#define TIMING_vfmsub_vv MKTIMING_UNKNOWN()
#define TIMING_vfmul_vf MKTIMING_UNKNOWN()
#define TIMING_vfmul_vv MKTIMING_UNKNOWN()
#define TIMING_vfmv_f_s MKTIMING_UNKNOWN()
#define TIMING_vfmv_s_f MKTIMING_UNKNOWN()
#define TIMING_vfmv_v_f MKTIMING_UNKNOWN()
#define TIMING_vfncvt_f_f_w MKTIMING_UNKNOWN()
#define TIMING_vfncvt_f_x_w MKTIMING_UNKNOWN()
#define TIMING_vfncvt_f_xu_w MKTIMING_UNKNOWN()
#define TIMING_vfncvt_rod_f_f_w MKTIMING_UNKNOWN()
#define TIMING_vfncvt_rtz_x_f_w MKTIMING_UNKNOWN()
#define TIMING_vfncvt_rtz_xu_f_w MKTIMING_UNKNOWN()
#define TIMING_vfncvt_x_f_w MKTIMING_UNKNOWN()
#define TIMING_vfncvt_xu_f_w MKTIMING_UNKNOWN()
#define TIMING_vfncvtbf16_f_f_w MKTIMING_UNKNOWN()
#define TIMING_vfnmacc_vf MKTIMING_UNKNOWN()
#define TIMING_vfnmacc_vv MKTIMING_UNKNOWN()
#define TIMING_vfnmadd_vf MKTIMING_UNKNOWN()
#define TIMING_vfnmadd_vv MKTIMING_UNKNOWN()
#define TIMING_vfnmsac_vf MKTIMING_UNKNOWN()
#define TIMING_vfnmsac_vv MKTIMING_UNKNOWN()
#define TIMING_vfnmsub_vf MKTIMING_UNKNOWN()
#define TIMING_vfnmsub_vv MKTIMING_UNKNOWN()
#define TIMING_vfrdiv_vf MKTIMING_UNKNOWN()
#define TIMING_vfrec7_v MKTIMING_UNKNOWN()
#define TIMING_vfredmax_vs MKTIMING_UNKNOWN()
#define TIMING_vfredmin_vs MKTIMING_UNKNOWN()
#define TIMING_vfredosum_vs MKTIMING_UNKNOWN()
#define TIMING_vfredusum_vs MKTIMING_UNKNOWN()
#define TIMING_vfrsqrt7_v MKTIMING_UNKNOWN()
#define TIMING_vfrsub_vf MKTIMING_UNKNOWN()
#define TIMING_vfsgnj_vf MKTIMING_UNKNOWN()
#define TIMING_vfsgnj_vv MKTIMING_UNKNOWN()
#define TIMING_vfsgnjn_vf MKTIMING_UNKNOWN()
#define TIMING_vfsgnjn_vv MKTIMING_UNKNOWN()
#define TIMING_vfsgnjx_vf MKTIMING_UNKNOWN()
#define TIMING_vfsgnjx_vv MKTIMING_UNKNOWN()
#define TIMING_vfslide1down_vf MKTIMING_UNKNOWN()
#define TIMING_vfslide1up_vf MKTIMING_UNKNOWN()
#define TIMING_vfsqrt_v MKTIMING_UNKNOWN()
#define TIMING_vfsub_vf MKTIMING_UNKNOWN()
#define TIMING_vfsub_vv MKTIMING_UNKNOWN()
#define TIMING_vfwadd_vf MKTIMING_UNKNOWN()
#define TIMING_vfwadd_vv MKTIMING_UNKNOWN()
#define TIMING_vfwadd_wf MKTIMING_UNKNOWN()
#define TIMING_vfwadd_wv MKTIMING_UNKNOWN()
#define TIMING_vfwcvt_f_f_v MKTIMING_UNKNOWN()
#define TIMING_vfwcvt_f_x_v MKTIMING_UNKNOWN()
#define TIMING_vfwcvt_f_xu_v MKTIMING_UNKNOWN()
#define TIMING_vfwcvt_rtz_x_f_v MKTIMING_UNKNOWN()
#define TIMING_vfwcvt_rtz_xu_f_v MKTIMING_UNKNOWN()
#define TIMING_vfwcvt_x_f_v MKTIMING_UNKNOWN()
#define TIMING_vfwcvt_xu_f_v MKTIMING_UNKNOWN()
#define TIMING_vfwcvtbf16_f_f_v MKTIMING_UNKNOWN()
#define TIMING_vfwmacc_vf MKTIMING_UNKNOWN()
#define TIMING_vfwmacc_vv MKTIMING_UNKNOWN()
#define TIMING_vfwmaccbf16_vf MKTIMING_UNKNOWN()
#define TIMING_vfwmaccbf16_vv MKTIMING_UNKNOWN()
#define TIMING_vfwmsac_vf MKTIMING_UNKNOWN()
#define TIMING_vfwmsac_vv MKTIMING_UNKNOWN()
#define TIMING_vfwmul_vf MKTIMING_UNKNOWN()
#define TIMING_vfwmul_vv MKTIMING_UNKNOWN()
#define TIMING_vfwnmacc_vf MKTIMING_UNKNOWN()
#define TIMING_vfwnmacc_vv MKTIMING_UNKNOWN()
#define TIMING_vfwnmsac_vf MKTIMING_UNKNOWN()
#define TIMING_vfwnmsac_vv MKTIMING_UNKNOWN()
#define TIMING_vfwredosum_vs MKTIMING_UNKNOWN()
#define TIMING_vfwredusum_vs MKTIMING_UNKNOWN()
#define TIMING_vfwsub_vf MKTIMING_UNKNOWN()
#define TIMING_vfwsub_vv MKTIMING_UNKNOWN()
#define TIMING_vfwsub_wf MKTIMING_UNKNOWN()
#define TIMING_vfwsub_wv MKTIMING_UNKNOWN()
#define TIMING_vghsh_vv MKTIMING_UNKNOWN()
#define TIMING_vgmul_vv MKTIMING_UNKNOWN()
#define TIMING_vid_v MKTIMING_UNKNOWN()
#define TIMING_viota_m MKTIMING_UNKNOWN()
#define TIMING_vl1re16_v MKTIMING_UNKNOWN()
#define TIMING_vl1re32_v MKTIMING_UNKNOWN()
#define TIMING_vl1re64_v MKTIMING_UNKNOWN()
#define TIMING_vl1re8_v MKTIMING_UNKNOWN()
#define TIMING_vl2re16_v MKTIMING_UNKNOWN()
#define TIMING_vl2re32_v MKTIMING_UNKNOWN()
#define TIMING_vl2re64_v MKTIMING_UNKNOWN()
#define TIMING_vl2re8_v MKTIMING_UNKNOWN()
#define TIMING_vl4re16_v MKTIMING_UNKNOWN()
#define TIMING_vl4re32_v MKTIMING_UNKNOWN()
#define TIMING_vl4re64_v MKTIMING_UNKNOWN()
#define TIMING_vl4re8_v MKTIMING_UNKNOWN()
#define TIMING_vl8re16_v MKTIMING_UNKNOWN()
#define TIMING_vl8re32_v MKTIMING_UNKNOWN()
#define TIMING_vl8re64_v MKTIMING_UNKNOWN()
#define TIMING_vl8re8_v MKTIMING_UNKNOWN()
#define TIMING_vle16_v MKTIMING_UNKNOWN()
#define TIMING_vle16ff_v MKTIMING_UNKNOWN()
#define TIMING_vle32_v MKTIMING_UNKNOWN()
#define TIMING_vle32ff_v MKTIMING_UNKNOWN()
#define TIMING_vle64_v MKTIMING_UNKNOWN()
#define TIMING_vle64ff_v MKTIMING_UNKNOWN()
#define TIMING_vle8_v MKTIMING_UNKNOWN()
#define TIMING_vle8ff_v MKTIMING_UNKNOWN()
#define TIMING_vlm_v MKTIMING_UNKNOWN()
#define TIMING_vloxei16_v MKTIMING_UNKNOWN()
#define TIMING_vloxei32_v MKTIMING_UNKNOWN()
#define TIMING_vloxei64_v MKTIMING_UNKNOWN()
#define TIMING_vloxei8_v MKTIMING_UNKNOWN()
#define TIMING_vlse16_v MKTIMING_UNKNOWN()
#define TIMING_vlse32_v MKTIMING_UNKNOWN()
#define TIMING_vlse64_v MKTIMING_UNKNOWN()
#define TIMING_vlse8_v MKTIMING_UNKNOWN()
#define TIMING_vluxei16_v MKTIMING_UNKNOWN()
#define TIMING_vluxei32_v MKTIMING_UNKNOWN()
#define TIMING_vluxei64_v MKTIMING_UNKNOWN()
#define TIMING_vluxei8_v MKTIMING_UNKNOWN()
#define TIMING_vmacc_vv MKTIMING_UNKNOWN()
#define TIMING_vmacc_vx MKTIMING_UNKNOWN()
#define TIMING_vmadc_vi MKTIMING_UNKNOWN()
#define TIMING_vmadc_vim MKTIMING_UNKNOWN()
#define TIMING_vmadc_vv MKTIMING_UNKNOWN()
#define TIMING_vmadc_vvm MKTIMING_UNKNOWN()
#define TIMING_vmadc_vx MKTIMING_UNKNOWN()
#define TIMING_vmadc_vxm MKTIMING_UNKNOWN()
#define TIMING_vmadd_vv MKTIMING_UNKNOWN()
#define TIMING_vmadd_vx MKTIMING_UNKNOWN()
#define TIMING_vmand_mm MKTIMING_UNKNOWN()
#define TIMING_vmandn_mm MKTIMING_UNKNOWN()
#define TIMING_vmax_vv MKTIMING_UNKNOWN()
#define TIMING_vmax_vx MKTIMING_UNKNOWN()
#define TIMING_vmaxu_vv MKTIMING_UNKNOWN()
#define TIMING_vmaxu_vx MKTIMING_UNKNOWN()
#define TIMING_vmerge_vim MKTIMING_UNKNOWN()
#define TIMING_vmerge_vvm MKTIMING_UNKNOWN()
#define TIMING_vmerge_vxm MKTIMING_UNKNOWN()
#define TIMING_vmfeq_vf MKTIMING_UNKNOWN()
#define TIMING_vmfeq_vv MKTIMING_UNKNOWN()
#define TIMING_vmfge_vf MKTIMING_UNKNOWN()
#define TIMING_vmfgt_vf MKTIMING_UNKNOWN()
#define TIMING_vmfle_vf MKTIMING_UNKNOWN()
#define TIMING_vmfle_vv MKTIMING_UNKNOWN()
#define TIMING_vmflt_vf MKTIMING_UNKNOWN()
#define TIMING_vmflt_vv MKTIMING_UNKNOWN()
#define TIMING_vmfne_vf MKTIMING_UNKNOWN()
#define TIMING_vmfne_vv MKTIMING_UNKNOWN()
#define TIMING_vmin_vv MKTIMING_UNKNOWN()
#define TIMING_vmin_vx MKTIMING_UNKNOWN()
#define TIMING_vminu_vv MKTIMING_UNKNOWN()
#define TIMING_vminu_vx MKTIMING_UNKNOWN()
#define TIMING_vmnand_mm MKTIMING_UNKNOWN()
#define TIMING_vmnor_mm MKTIMING_UNKNOWN()
#define TIMING_vmor_mm MKTIMING_UNKNOWN()
#define TIMING_vmorn_mm MKTIMING_UNKNOWN()
#define TIMING_vmsbc_vv MKTIMING_UNKNOWN()
#define TIMING_vmsbc_vvm MKTIMING_UNKNOWN()
#define TIMING_vmsbc_vx MKTIMING_UNKNOWN()
#define TIMING_vmsbc_vxm MKTIMING_UNKNOWN()
#define TIMING_vmsbf_m MKTIMING_UNKNOWN()
#define TIMING_vmseq_vi MKTIMING_UNKNOWN()
#define TIMING_vmseq_vv MKTIMING_UNKNOWN()
#define TIMING_vmseq_vx MKTIMING_UNKNOWN()
#define TIMING_vmsgt_vi MKTIMING_UNKNOWN()
#define TIMING_vmsgt_vx MKTIMING_UNKNOWN()
#define TIMING_vmsgtu_vi MKTIMING_UNKNOWN()
#define TIMING_vmsgtu_vx MKTIMING_UNKNOWN()
#define TIMING_vmsif_m MKTIMING_UNKNOWN()
#define TIMING_vmsle_vi MKTIMING_UNKNOWN()
#define TIMING_vmsle_vv MKTIMING_UNKNOWN()
#define TIMING_vmsle_vx MKTIMING_UNKNOWN()
#define TIMING_vmsleu_vi MKTIMING_UNKNOWN()
#define TIMING_vmsleu_vv MKTIMING_UNKNOWN()
#define TIMING_vmsleu_vx MKTIMING_UNKNOWN()
#define TIMING_vmslt_vv MKTIMING_UNKNOWN()
#define TIMING_vmslt_vx MKTIMING_UNKNOWN()
#define TIMING_vmsltu_vv MKTIMING_UNKNOWN()
#define TIMING_vmsltu_vx MKTIMING_UNKNOWN()
#define TIMING_vmsne_vi MKTIMING_UNKNOWN()
#define TIMING_vmsne_vv MKTIMING_UNKNOWN()
#define TIMING_vmsne_vx MKTIMING_UNKNOWN()
#define TIMING_vmsof_m MKTIMING_UNKNOWN()
#define TIMING_vmul_vv MKTIMING_UNKNOWN()
#define TIMING_vmul_vx MKTIMING_UNKNOWN()
#define TIMING_vmulh_vv MKTIMING_UNKNOWN()
#define TIMING_vmulh_vx MKTIMING_UNKNOWN()
#define TIMING_vmulhsu_vv MKTIMING_UNKNOWN()
#define TIMING_vmulhsu_vx MKTIMING_UNKNOWN()
#define TIMING_vmulhu_vv MKTIMING_UNKNOWN()
#define TIMING_vmulhu_vx MKTIMING_UNKNOWN()
#define TIMING_vmv1r_v MKTIMING_UNKNOWN()
#define TIMING_vmv2r_v MKTIMING_UNKNOWN()
#define TIMING_vmv4r_v MKTIMING_UNKNOWN()
#define TIMING_vmv8r_v MKTIMING_UNKNOWN()
#define TIMING_vmv_s_x MKTIMING_UNKNOWN()
#define TIMING_vmv_v_i MKTIMING_UNKNOWN()
#define TIMING_vmv_v_v MKTIMING_UNKNOWN()
#define TIMING_vmv_v_x MKTIMING_UNKNOWN()
#define TIMING_vmv_x_s MKTIMING_UNKNOWN()
#define TIMING_vmxnor_mm MKTIMING_UNKNOWN()
#define TIMING_vmxor_mm MKTIMING_UNKNOWN()
#define TIMING_vnclip_wi MKTIMING_UNKNOWN()
#define TIMING_vnclip_wv MKTIMING_UNKNOWN()
#define TIMING_vnclip_wx MKTIMING_UNKNOWN()
#define TIMING_vnclipu_wi MKTIMING_UNKNOWN()
#define TIMING_vnclipu_wv MKTIMING_UNKNOWN()
#define TIMING_vnclipu_wx MKTIMING_UNKNOWN()
#define TIMING_vnmsac_vv MKTIMING_UNKNOWN()
#define TIMING_vnmsac_vx MKTIMING_UNKNOWN()
#define TIMING_vnmsub_vv MKTIMING_UNKNOWN()
#define TIMING_vnmsub_vx MKTIMING_UNKNOWN()
#define TIMING_vnsra_wi MKTIMING_UNKNOWN()
#define TIMING_vnsra_wv MKTIMING_UNKNOWN()
#define TIMING_vnsra_wx MKTIMING_UNKNOWN()
#define TIMING_vnsrl_wi MKTIMING_UNKNOWN()
#define TIMING_vnsrl_wv MKTIMING_UNKNOWN()
#define TIMING_vnsrl_wx MKTIMING_UNKNOWN()
#define TIMING_vor_vi MKTIMING_UNKNOWN()
#define TIMING_vor_vv MKTIMING_UNKNOWN()
#define TIMING_vor_vx MKTIMING_UNKNOWN()
#define TIMING_vqdot_vv MKTIMING_UNKNOWN()
#define TIMING_vqdot_vx MKTIMING_UNKNOWN()
#define TIMING_vqdotsu_vv MKTIMING_UNKNOWN()
#define TIMING_vqdotsu_vx MKTIMING_UNKNOWN()
#define TIMING_vqdotu_vv MKTIMING_UNKNOWN()
#define TIMING_vqdotu_vx MKTIMING_UNKNOWN()
#define TIMING_vqdotus_vx MKTIMING_UNKNOWN()
#define TIMING_vredand_vs MKTIMING_UNKNOWN()
#define TIMING_vredmax_vs MKTIMING_UNKNOWN()
#define TIMING_vredmaxu_vs MKTIMING_UNKNOWN()
#define TIMING_vredmin_vs MKTIMING_UNKNOWN()
#define TIMING_vredminu_vs MKTIMING_UNKNOWN()
#define TIMING_vredor_vs MKTIMING_UNKNOWN()
#define TIMING_vredsum_vs MKTIMING_UNKNOWN()
#define TIMING_vredxor_vs MKTIMING_UNKNOWN()
#define TIMING_vrem_vv MKTIMING_UNKNOWN()
#define TIMING_vrem_vx MKTIMING_UNKNOWN()
#define TIMING_vremu_vv MKTIMING_UNKNOWN()
#define TIMING_vremu_vx MKTIMING_UNKNOWN()
#define TIMING_vrev8_v MKTIMING_UNKNOWN()
#define TIMING_vrgather_vi MKTIMING_UNKNOWN()
#define TIMING_vrgather_vv MKTIMING_UNKNOWN()
#define TIMING_vrgather_vx MKTIMING_UNKNOWN()
#define TIMING_vrgatherei16_vv MKTIMING_UNKNOWN()
#define TIMING_vrol_vv MKTIMING_UNKNOWN()
#define TIMING_vrol_vx MKTIMING_UNKNOWN()
#define TIMING_vror_vi MKTIMING_UNKNOWN()
#define TIMING_vror_vv MKTIMING_UNKNOWN()
#define TIMING_vror_vx MKTIMING_UNKNOWN()
#define TIMING_vrsub_vi MKTIMING_UNKNOWN()
#define TIMING_vrsub_vx MKTIMING_UNKNOWN()
#define TIMING_vs1r_v MKTIMING_UNKNOWN()
#define TIMING_vs2r_v MKTIMING_UNKNOWN()
#define TIMING_vs4r_v MKTIMING_UNKNOWN()
#define TIMING_vs8r_v MKTIMING_UNKNOWN()
#define TIMING_vsadd_vi MKTIMING_UNKNOWN()
#define TIMING_vsadd_vv MKTIMING_UNKNOWN()
#define TIMING_vsadd_vx MKTIMING_UNKNOWN()
#define TIMING_vsaddu_vi MKTIMING_UNKNOWN()
#define TIMING_vsaddu_vv MKTIMING_UNKNOWN()
#define TIMING_vsaddu_vx MKTIMING_UNKNOWN()
#define TIMING_vsbc_vvm MKTIMING_UNKNOWN()
#define TIMING_vsbc_vxm MKTIMING_UNKNOWN()
#define TIMING_vse16_v MKTIMING_UNKNOWN()
#define TIMING_vse32_v MKTIMING_UNKNOWN()
#define TIMING_vse64_v MKTIMING_UNKNOWN()
#define TIMING_vse8_v MKTIMING_UNKNOWN()
#define TIMING_vsetivli MKTIMING_UNKNOWN()
#define TIMING_vsetvl MKTIMING_UNKNOWN()
#define TIMING_vsetvli MKTIMING_UNKNOWN()
#define TIMING_vsext_vf2 MKTIMING_UNKNOWN()
#define TIMING_vsext_vf4 MKTIMING_UNKNOWN()
#define TIMING_vsext_vf8 MKTIMING_UNKNOWN()
#define TIMING_vsha2ch_vv MKTIMING_UNKNOWN()
#define TIMING_vsha2cl_vv MKTIMING_UNKNOWN()
#define TIMING_vsha2ms_vv MKTIMING_UNKNOWN()
#define TIMING_vslide1down_vx MKTIMING_UNKNOWN()
#define TIMING_vslide1up_vx MKTIMING_UNKNOWN()
#define TIMING_vslidedown_vi MKTIMING_UNKNOWN()
#define TIMING_vslidedown_vx MKTIMING_UNKNOWN()
#define TIMING_vslideup_vi MKTIMING_UNKNOWN()
#define TIMING_vslideup_vx MKTIMING_UNKNOWN()
#define TIMING_vsll_vi MKTIMING_UNKNOWN()
#define TIMING_vsll_vv MKTIMING_UNKNOWN()
#define TIMING_vsll_vx MKTIMING_UNKNOWN()
#define TIMING_vsm3c_vi MKTIMING_UNKNOWN()
#define TIMING_vsm3me_vv MKTIMING_UNKNOWN()
#define TIMING_vsm4k_vi MKTIMING_UNKNOWN()
#define TIMING_vsm4r_vs MKTIMING_UNKNOWN()
#define TIMING_vsm4r_vv MKTIMING_UNKNOWN()
#define TIMING_vsm_v MKTIMING_UNKNOWN()
#define TIMING_vsmul_vv MKTIMING_UNKNOWN()
#define TIMING_vsmul_vx MKTIMING_UNKNOWN()
#define TIMING_vsoxei16_v MKTIMING_UNKNOWN()
#define TIMING_vsoxei32_v MKTIMING_UNKNOWN()
#define TIMING_vsoxei64_v MKTIMING_UNKNOWN()
#define TIMING_vsoxei8_v MKTIMING_UNKNOWN()
#define TIMING_vsra_vi MKTIMING_UNKNOWN()
#define TIMING_vsra_vv MKTIMING_UNKNOWN()
#define TIMING_vsra_vx MKTIMING_UNKNOWN()
#define TIMING_vsrl_vi MKTIMING_UNKNOWN()
#define TIMING_vsrl_vv MKTIMING_UNKNOWN()
#define TIMING_vsrl_vx MKTIMING_UNKNOWN()
#define TIMING_vsse16_v MKTIMING_UNKNOWN()
#define TIMING_vsse32_v MKTIMING_UNKNOWN()
#define TIMING_vsse64_v MKTIMING_UNKNOWN()
#define TIMING_vsse8_v MKTIMING_UNKNOWN()
#define TIMING_vssra_vi MKTIMING_UNKNOWN()
#define TIMING_vssra_vv MKTIMING_UNKNOWN()
#define TIMING_vssra_vx MKTIMING_UNKNOWN()
#define TIMING_vssrl_vi MKTIMING_UNKNOWN()
#define TIMING_vssrl_vv MKTIMING_UNKNOWN()
#define TIMING_vssrl_vx MKTIMING_UNKNOWN()
#define TIMING_vssub_vv MKTIMING_UNKNOWN()
#define TIMING_vssub_vx MKTIMING_UNKNOWN()
#define TIMING_vssubu_vv MKTIMING_UNKNOWN()
#define TIMING_vssubu_vx MKTIMING_UNKNOWN()
#define TIMING_vsub_vv MKTIMING_UNKNOWN()
#define TIMING_vsub_vx MKTIMING_UNKNOWN()
#define TIMING_vsuxei16_v MKTIMING_UNKNOWN()
#define TIMING_vsuxei32_v MKTIMING_UNKNOWN()
#define TIMING_vsuxei64_v MKTIMING_UNKNOWN()
#define TIMING_vsuxei8_v MKTIMING_UNKNOWN()
#define TIMING_vwadd_vv MKTIMING_UNKNOWN()
#define TIMING_vwadd_vx MKTIMING_UNKNOWN()
#define TIMING_vwadd_wv MKTIMING_UNKNOWN()
#define TIMING_vwadd_wx MKTIMING_UNKNOWN()
#define TIMING_vwaddu_vv MKTIMING_UNKNOWN()
#define TIMING_vwaddu_vx MKTIMING_UNKNOWN()
#define TIMING_vwaddu_wv MKTIMING_UNKNOWN()
#define TIMING_vwaddu_wx MKTIMING_UNKNOWN()
#define TIMING_vwmacc_vv MKTIMING_UNKNOWN()
#define TIMING_vwmacc_vx MKTIMING_UNKNOWN()
#define TIMING_vwmaccsu_vv MKTIMING_UNKNOWN()
#define TIMING_vwmaccsu_vx MKTIMING_UNKNOWN()
#define TIMING_vwmaccu_vv MKTIMING_UNKNOWN()
#define TIMING_vwmaccu_vx MKTIMING_UNKNOWN()
#define TIMING_vwmaccus_vx MKTIMING_UNKNOWN()
#define TIMING_vwmul_vv MKTIMING_UNKNOWN()
#define TIMING_vwmul_vx MKTIMING_UNKNOWN()
#define TIMING_vwmulsu_vv MKTIMING_UNKNOWN()
#define TIMING_vwmulsu_vx MKTIMING_UNKNOWN()
#define TIMING_vwmulu_vv MKTIMING_UNKNOWN()
#define TIMING_vwmulu_vx MKTIMING_UNKNOWN()
#define TIMING_vwredsum_vs MKTIMING_UNKNOWN()
#define TIMING_vwredsumu_vs MKTIMING_UNKNOWN()
#define TIMING_vwsll_vi MKTIMING_UNKNOWN()
#define TIMING_vwsll_vv MKTIMING_UNKNOWN()
#define TIMING_vwsll_vx MKTIMING_UNKNOWN()
#define TIMING_vwsub_vv MKTIMING_UNKNOWN()
#define TIMING_vwsub_vx MKTIMING_UNKNOWN()
#define TIMING_vwsub_wv MKTIMING_UNKNOWN()
#define TIMING_vwsub_wx MKTIMING_UNKNOWN()
#define TIMING_vwsubu_vv MKTIMING_UNKNOWN()
#define TIMING_vwsubu_vx MKTIMING_UNKNOWN()
#define TIMING_vwsubu_wv MKTIMING_UNKNOWN()
#define TIMING_vwsubu_wx MKTIMING_UNKNOWN()
#define TIMING_vxor_vi MKTIMING_UNKNOWN()
#define TIMING_vxor_vv MKTIMING_UNKNOWN()
#define TIMING_vxor_vx MKTIMING_UNKNOWN()
#define TIMING_vzext_vf2 MKTIMING_UNKNOWN()
#define TIMING_vzext_vf4 MKTIMING_UNKNOWN()
#define TIMING_vzext_vf8 MKTIMING_UNKNOWN()
#define TIMING_wfi MKTIMING_UNKNOWN()
#define TIMING_wrs_nto MKTIMING_UNKNOWN()
#define TIMING_wrs_sto MKTIMING_UNKNOWN()
#define TIMING_xnor       MKTIMING_ARITH(XNOR)
#define TIMING_xor        MKTIMING_ARITH(XOR)
#define TIMING_xori       MKTIMING_ARITH(XOR)
#define TIMING_xperm16 MKTIMING_UNKNOWN()
#define TIMING_xperm32 MKTIMING_UNKNOWN()
#define TIMING_xperm4 MKTIMING_UNKNOWN()
#define TIMING_xperm8 MKTIMING_UNKNOWN()
#define TIMING_c_beq      MKTIMING_JB(BCOND)
#define TIMING_c_bne      MKTIMING_JB(BCOND)
#define TIMING_c_auipc    MKTIMING_ARITH(AUIPC)
#define TIMING_c_mulh     MKTIMING_MUL(MULH)
#define TIMING_c_mulhu    MKTIMING_MUL(MULHU)
#define TIMING_c_neg      MKTIMING_ARITH(NEG)
#define TIMING_c_addi2w   MKTIMING_ARITH(ADD)
#define TIMING_c_add2     MKTIMING_ARITH(ADD)
#define TIMING_c_seqz     MKTIMING_ARITH(SEQ)
#define TIMING_c_snez     MKTIMING_ARITH(SEQ)
#define TIMING_c_addi2b   MKTIMING_ARITH(ADD)
#define TIMING_c_slt      MKTIMING_ARITH(SLT)
#define TIMING_c_sltu     MKTIMING_ARITH(SLTU)
#define TIMING_c_lb       MKTIMING_LD(LB)
#define TIMING_c_lbu      MKTIMING_LD(LB)
#define TIMING_c_lh       MKTIMING_LD(LH)
#define TIMING_c_lhu      MKTIMING_LD(LH)
#define TIMING_c_sb       MKTIMING_ST(SB)
#define TIMING_c_sh       MKTIMING_ST(SH)
#define TIMING_c_sb0      MKTIMING_ST(SB)
#define TIMING_c_sh0      MKTIMING_ST(SH)
#define TIMING_c_sw0      MKTIMING_ST(SW)
#define TIMING_cmov       MKTIMING_ARITH(CMOV)
#define TIMING_fsl        MKTIMING_ARITH(FSL)
#define TIMING_fsr        MKTIMING_ARITH(FSR)
#define TIMING_fsri       MKTIMING_ARITH(FSR)
#define TIMING_bfx        MKTIMING_ARITH(BFX)
#define TIMING_bfs        MKTIMING_ARITH(BFS)
#define TIMING_bff        MKTIMING_ARITH(BFF)
#define TIMING_bfa        MKTIMING_ARITH(BFA)
#define TIMING_bfm        MKTIMING_ARITH(BFM)
#define TIMING_bfp        MKTIMING_ARITH(BFP)
#define TIMING_bfap       MKTIMING_ARITH(BFA)
#define TIMING_bfmp       MKTIMING_ARITH(BFM)
#define TIMING_bfpp       MKTIMING_ARITH(BFP)
#define TIMING_bfxi       MKTIMING_ARITH(BFX)
#define TIMING_bfsi       MKTIMING_ARITH(BFS)
#define TIMING_bffi       MKTIMING_ARITH(BFF)
#define TIMING_bfai       MKTIMING_ARITH(BFA)
#define TIMING_bfmi       MKTIMING_ARITH(BFM)
#define TIMING_bfpi       MKTIMING_ARITH(BFP)
#define TIMING_bsct_h MKTIMING_UNKNOWN()
#define TIMING_seq        MKTIMING_ARITH(SEQ)
#define TIMING_sne        MKTIMING_ARITH(SEQ)
#define TIMING_seqi       MKTIMING_ARITH(SEQ)
#define TIMING_snei       MKTIMING_ARITH(SEQ)

#endif
