[build]
target = "riscv32imc-cramp-none-elf"
rustflags = ["-C", "relocation-model=pic", "-C", "target-feature=+zba,+zbb,+zbs,+xcramp,+relax"]
# rustflags = ["-C", "relocation-model=pic", "-C", "target-feature=+zba,+zbb,+zbs,+xcramp,+relax", "--emit=llvm-ir"]
# rustflags = ["-C", "relocation-model=pic", "-C", "target-feature=+zba,+zbb,+zbs,+xcramp,+relax", "-C", "llvm-args=-view-isel-dags"]
